### PR TITLE
Support Flutter Web

### PR DESCRIPTION
**Pull request by ariejan**
This is still a work in progress, creating this PR now to see how Github Actions will respond.

### CODE REVIEW

**Comment by frank06** [comment]
Appreciate the PR, before any merge I'd like to make sure we have ongoing web support: https://github.com/flutterdata/flutter_data/issues/185

**Comment by ariejan** [comment]
@frank06 that was the point of the PR ;-) 

 1. Could you, @frank06 approve this PR for Github Actions? So, not an approval of the PR, but just to run github actions.
 2. Right now web tests are run with `-p chrome` which seems to fail. Running `-p firefox` shows green tests. Right now I think there's something wrong with running tests and/or mockito on chrome (not "web" as a whole).

Once Github Actions is active, I can test my changes more thoroughly.

**Comment by ariejan** [comment]
Looking further into failing tests for web, they all share one thing: `await oneMs()` from [setup.dart](https://github.com/flutterdata/flutter_data/blob/master/test/_support/setup.dart#L128). The goal is to let things settle before making assertions, however, on slower systems when running in-browser tests this is not enough time.

I bumped the duration in `oneMs` to 10ms and that makes all tests pass without issue.

**Comment by frank06** [comment]
Makes sense, thank you!  I have encountered other issues on web in the past that were not related to timing, and these were very difficult to debug. Hopefully things get better

**Pull request merged**
