### PR TITLE
Refactor CI pipeline to test all supported platforms

### PR DESCRIPTION
**Pull request by Skycoder42**
Due to #149 I took a look at your CI and would like to contribute the following improvements with the goal to have all tests run on all supported platforms, which should catch bugs similar to that one and ensures consistency across all platforms.

The first commit refactors the CI pipeline. The following changes have been made:
- Instead of a docker image, VM images are used
- the pipeline is now a matrix pipeline, that runs tests for linux, windows, macos and in the browser (chrome)
- Uses the official setup task for dart (latest stable)
- Modernized usage of the dart commands (e.g. `dart test` instead of `pub test`)
- Coverage is only generated and published for the linux run

The second commit updates the tests to work within the browser. Two changes have been made:
- The local storage hive test is simply skipped for now. However, since hive is supported on the web, it might be a good idea to update the test so it works in the web as well https://pub.dev/packages/universal_io might be of help
- Apparently, `Node` is a reserved type in the browser, which is why the Node type of the repository gets compiled to `Node1` in the web, thus the pluralized path is wrong (`node1s` instead of `nodes`). For now, I simply replaces the adapter key for web tests, however, it might be best to simply rename the type to something like `MyNode` instead.

### CODE REVIEW

**Comment by frank06** [comment]
Fantastic! Thank you very much.

For now we'll leave the Hive local storage test out. I appreciate the heads up

**Comment by frank06** [comment]
@Skycoder42 The latest build is failing only on web.

Would you have any idea as to what the following error could mean? I spent the last hour trying to understand without success.

https://github.com/flutterdata/flutter_data/runs/5763078230?check_suite_focus=true#step:5:2763

Until that gets figured out, I will disable automated testing on the web platform.

**Comment by Skycoder42** [comment]
@frank06 sure, I'll take a look at it. The error seems very similar to the ones I initially had when adding the web tests

**Comment by Skycoder42** [comment]
Okay, so I took a look at it, and apparently, "Familiy" is also a reserved JS type, as the types name is "Family0" in JS... this again breaks everything.

**Comment by Skycoder42** [comment]
See #152

**Pull request merged**
